#!/usr/bin/env bash
set -euo pipefail

# Enforces "Artefactos De Generación Prohibidos" (see AGENTS.md).
# Scans only tracked files to avoid noise from dependencies or build output.
if ! command -v git >/dev/null 2>&1; then
  echo "FAIL: git is required" >&2
  exit 1
fi

# This script is allowed to mention the forbidden phrases for detection purposes.
# Governance files must also reference the phrases to define the policy itself.
allowlist='scripts/check-tracked-no-ai-artifacts.sh|AGENTS.md|.github/instructions/tiggreeeon-governance.instructions.md'

patterns=(
  "Inventario de Generaci" \
  "Fecha de Generaci" \
  "Generation date" \
  "Generated by AI" \
  "LISTO PARA PRODUCCI" \
  "Proyecciones de Ingresos" \
)

found=0
for pattern in "${patterns[@]}"; do
  matches="$(git ls-files | grep -v -E "${allowlist}" | xargs grep -nH -F "${pattern}" 2>/dev/null || true)"
  if [[ -n "${matches}" ]]; then
    echo "FAIL: forbidden generation artifact found (\"${pattern}\"):"
    echo "${matches}"
    found=1
  fi
done

# Emoji status markers in tracked markdown (excluding governance/policy files).
emoji_matches="$(git ls-files '*.md' | grep -v -E "${allowlist}" | xargs grep -nHP '[\x{1F000}-\x{1FAFF}\x{2600}-\x{27BF}\x{2B00}-\x{2BFF}]' 2>/dev/null || true)"
if [[ -n "${emoji_matches}" ]]; then
  echo "FAIL: emoji status markers found in tracked markdown:"
  echo "${emoji_matches}"
  found=1
fi

if [[ "${found}" -ne 0 ]]; then
  exit 1
fi

echo "PASS: no forbidden generation artifacts found in tracked files."
